davmail.imapAutoExpunge=true
davmail.ssl.keyPass=
davmail.caldavAutoSchedule=true
davmail.enableOidc=true
davmail.mode=O365Modern
davmail.oauth.redirectUri=
davmail.url=https://outlook.office365.com/EWS/Exchange.asmx
log4j.logger.httpclient.wire=WARN
davmail.ssl.clientKeystoreType=
davmail.ssl.nosecureimap=false
log4j.logger.org.apache.http=WARN
davmail.imapAlwaysApproxMsgSize=false
davmail.enableProxy=false
davmail.logFilePath=davmail.log
davmail.ssl.clientKeystorePass=
davmail.smtpPort=1025
davmail.caldavPort=1080
davmail.disableUpdateCheck=false
davmail.bindAddress=
davmail.keepDelay=30
davmail.enableKerberos=false
davmail.ssl.nosecurepop=false
davmail.oauth.tenantId=
davmail.ssl.nosecuresmtp=false
log4j.rootLogger=WARN
davmail.proxyHost=
davmail.useSystemProxies=false
log4j.logger.org.apache.http.wire=WARN
davmail.popPort=
davmail.clientSoTimeout=
log4j.logger.davmail=WARN
davmail.showStartupBanner=true
log4j.logger.org.apache.commons.httpclient=WARN
davmail.ssl.nosecureldap=false
davmail.allowRemote=false
davmail.enableKeepAlive=false
davmail.oauth.persistToken=true
davmail.popMarkReadOnRetr=false
davmail.ldapPort=1389
davmail.sentKeepDelay=0
davmail.server=false
davmail.disableGuiNotifications=true
davmail.imapPort=1143
davmail.caldavPastDelay=0
davmail.oauth.clientId=
davmail.caldavAlarmSound=
davmail.server.certificate.hash=
davmail.noProxyFor=
davmail.imapIdleDelay=
davmail.ssl.keystoreFile=
davmail.ssl.pkcs11Library=
davmail.proxyPort=
davmail.imapFlags.holiday=Holiday
davmail.carddavReadPhoto=true
davmail.imapFlags.$label5=Later
davmail.forceActiveSyncUpdate=false
davmail.proxyPassword=
davmail.imapFlags.$label4=ToDo
davmail.imapFlags.$label3=Personal
davmail.imapFlags.$label2=Business
davmail.defaultDomain=
davmail.imapFlags.$label1=Important
davmail.disableTrayActivitySwitch=true
davmail.proxyUser=
davmail.smtpSaveInSent=false
davmail.ssl.clientKeystoreFile=
davmail.caldavEditNotifications=false
davmail.ssl.keystoreType=
davmail.ssl.pkcs11Config=
davmail.folderSizeLimit=
davmail.ssl.nosecurecaldav=false
davmail.ssl.keystorePass=
davmail.logFileSize=
